name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: 
      - debian-node
      - fast
    steps:
      - uses: https://github.com/actions/checkout@v4

      - uses: https://github.com/actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: go test
        run: go test ./...

      - name: go build
        run: go build -trimpath -ldflags="-s -w" -o bin/archiveopds ./cmd/archiveopds
